Checkers draw
kowalakk/BoardGameTrainer pull request #39
Opened 2023-06-13 16:26 UTC by kowalakk

Set draw to occur after 15 moves that don't change the board in any significant manner. 
Fixed tests to work with CancellationToken. 
Added new tests.

2023-06-13 19:49 UTC, ztyszka requested changes

2023-06-13 19:49 UTC, ztyszka commented on Game.Checkers/CheckersAction/MoveAction.cs
> +                newState.InsignificantActions++;
tylko akcje, w których nie ma bicia są tymi, które należy zliczać, a po każdym biciu ten licznik powinien być zerowany

2023-06-13 19:51 UTC, ztyszka commented
Wydaje mi się, że zbytnio uprościłeś problem, bo to nie każdy ruch damką będzie taką insignificantAction, tylko każdy ruch KTÓRY NIE POWODUJE BICIA (i niekoniecznie damką). A po każdym biciu licznik insignificantAction powinien się resetować

2023-06-15 21:26 UTC, kowalakk commented on Game.Checkers/CheckersAction/MoveAction.cs
> +                newState.InsignificantActions++;
Teraz powinno działać.

2023-06-16 15:03 UTC, ztyszka requested changes

2023-06-16 15:03 UTC, ztyszka commented on Game.Checkers/CheckersAction/MoveAction.cs
> +                newState.InsignificantActions = 0;
reset licznika powinien następować w momencie wystąpienia bicia, a nie w przypadku ruchu zwykłym pionkiem

2023-06-16 15:03 UTC, ztyszka commented on Game.Checkers/CheckersAction/MoveAction.cs
> +                newState.InsignificantActions++;
nadal zliczamy tylko ruchy damek, a zwykkłych pionków nie

2023-06-20 10:48 UTC, ztyszka approved these changes

2023-06-20 11:34 UTC, merged