Bugfix/bug in gtk
kowalakk/BoardGameTrainer pull request #40
Opened 2023-06-14 01:04 UTC by kowalakk

Refactoring 
Issue [#32] partially fixed
Issue [#20] fixed

2023-06-18 21:33 UTC, ztyszka requested changes

2023-06-18 21:33 UTC, ztyszka commented on BoardGameTrainer/Application/ConfigWindow.cs
> +            { "Nested Monte Carlo Search", new NmcsFactory(3) }
może użyjmy nazwanych stałych do tego?

2023-06-18 21:33 UTC, ztyszka commented on BoardGameTrainer/Application/ConfigWindow.cs
> +            newGameButton.Clicked += (sender, args) =>
dla porządku kodu można umieścić tworzenie przycisku i jego obsługę za tworzenie stop condition boxa

2023-06-18 21:33 UTC, ztyszka commented on BoardGameTrainer/Application/MainWindow.cs
> +        private double X { get; set; }
prywatne property brzmi jak jakieś dziwactwo? co było złego ze zwykłym [private] double x;?

2023-06-18 21:33 UTC, ztyszka commented on BoardGameTrainer/Application/MainWindow.cs
> +                PerformMovement();
czemu tego już nie kolejkujemy?

2023-06-18 21:33 UTC, ztyszka commented on BoardGameTrainer/Application/MainWindow.cs
> +                CancellationToken token = ResetToken();
czy to, że resetujemy token dopiero tutaj nie oznacza, że mogą się nam wyświetlić jakieś przedawnione podpowiedzi zanim się wykona ten ruch?
Z drugiej strony poprzednie rozwiązanie chyba nadgorliwie cancellowało liczenie podpowiedzi

2023-06-18 21:33 UTC, ztyszka commented on BoardGameTrainer/Application/MainWindow.cs
> +        public CancellationToken ResetToken()
używamy tego gdzieś indziej, że potrzebujemy publicznej metody?

2023-06-18 21:33 UTC, ztyszka commented on BoardGameTrainer/CustomWidgets/StopConditionFrame.cs
> +            Boxes[0] = new(1000, 100000, 100, Param, "miliseconds");
Czemu nie możemy zejść poniżej 1000 ms? to dość długi czas
Dałabym 100ms jako dolne ograniczenie

2023-06-18 21:33 UTC, ztyszka commented on BoardGameTrainer/CustomWidgets/StopConditionFrame.cs
> +            Boxes[1] = new(1000, 100000, 100, Param, "iterations");
tu też można rozważyć niższą dolną granicę

2023-06-18 21:33 UTC, ztyszka commented on Game.IGame/Ai/GameTree.cs
> -            throw new ArgumentException();
czemu nie rzucamy już tego wyjątku?

2023-06-18 21:33 UTC, ztyszka commented on Game.IGame/GameManager/GameManager.cs
> +            CancellationTokenSource tokenSource = new();
przed tym chyba powinniśmy cancellować stary token

2023-06-18 21:33 UTC, ztyszka commented on Game.IGame/GameManager/GameManager.cs
> +            ratedActions = ai.MoveAssessment(gameTree, tokenSource.Token);
potrzebujemy też resetować currentPlayera

2023-06-20 11:20 UTC, kowalakk commented on Game.IGame/Ai/GameTree.cs
> -            throw new ArgumentException();
Jest jako issue

2023-06-20 11:38 UTC, ztyszka approved these changes

2023-06-22 17:56 UTC, merged