Game othello
kowalakk/BoardGameTrainer pull request #6
Opened 2022-12-13 21:27 UTC by ztyszka

2022-12-17 15:13 UTC, kowalakk requested changes

2022-12-17 15:13 UTC, kowalakk commented on Game.Othello/Othello.cs
> +            while(i > 0)
Nie sprawdzasz diagonali, a też miały być. Plus 4 powtórzenia kodu, można by zrobić oddzielną funkcję do tego. Spójrz sobie na Checkers.GetDiagsData(), ona generuje mi wszystkie możliwości i ustala zakres, żebym nie wyszedł poza planszę. U Ciebie trzeba by ją rozbudować o zwykłe wiersze i kolumny. A tu zrobić:
foreach ((int dCol, int dRow, int limit) in GetDiagsData((x,y)))
{
                int col = x + dCol;
                int row = y + dRow;
                int fieldsToCheck = limit;
                while (fieldsToCheck > 1 && board[col, row] == oponentsColor)
                {
                    col += dCol;
                    row += dRow;
                    fieldsToCheck--;
                }
                if (board[col, row] == playersColor)
                {
                      while (fieldsToCheck < limit)
                     {
                          col -= dCol;
                          row -= dRow;
                          board[col, row] = playersColor;
                          fieldsToCheck++;
                     }
                }
 }

2022-12-17 15:13 UTC, kowalakk commented on Game.Othello/Othello.cs
> +                return new List<OthelloAction>();
Czemu zwracasz pustą listę a nie listę z pustą akcją?

2022-12-17 15:13 UTC, kowalakk commented on Game.Othello/Othello.cs
> +            while(i > 0)
Albo w ogóle tego nie sprawdzać, tylko trzymać w akcji info ile odwraca pionków w każdym z ośmiu kierunków. Tak nawet lepiej.

2022-12-17 15:13 UTC, kowalakk commented on Game.Othello/Othello.cs
> +                // sprawdzenie w każdym z 4 kierunków czy sąsiaduje z szeregiem pionków przeciwnika, zakończonym własnym pionkiem
Znów powtórzenie kodu 4 razy. Też można by wykorzystać GetDiagsData() i zrobić foreach'a. Nawet lepiej tutaj i zapisać ile kamieni odwracamy w każdą stronę, a przy ruchu tylko odwrócić. Plus dlaczego akcja jest możliwa tylko gdy odwraca jakieś kamienie przeciwnika? Nie mogę sobie zwyczajnie dołożyć kamienia i niczego nie odwracać?

2022-12-17 15:13 UTC, kowalakk commented on Game.Othello/OthelloFullAction.cs
> +            if (position.Item1 >= 8 || position.Item2 >= 8
Akcje są generowane przez nasz kod, więc są poprawne z założenia. Sprawdzanie tylko spowalnia działanie programu.

2022-12-17 15:13 UTC, kowalakk commented on Game.Othello/OthelloFullAction.cs
> +            if (other.GetType() == typeof(OthelloEmptyAction))
Czemu piszesz tak, a nie "other is OthelloEmptyAction"?
No i other może być nullem.

2022-12-17 15:13 UTC, kowalakk commented on Game.Othello/OthelloState.cs
> +                throw new ArgumentException("incorrect white hand size");
board też tworzy nasz program, więc jest poprawny z założenia.

2022-12-17 16:05 UTC, ztyszka commented on Game.Othello/Othello.cs
> +            while(i > 0)
o, zwiększenie informacji zawartych w akcji to dobry pomysł

2022-12-17 16:05 UTC, ztyszka commented on Game.Othello/Othello.cs
> +                // sprawdzenie w każdym z 4 kierunków czy sąsiaduje z szeregiem pionków przeciwnika, zakończonym własnym pionkiem
nie, nie można dołożyć kamienia bez obracania

2022-12-17 21:27 UTC, ztyszka commented on Game.Othello/Othello.cs
> +            while(i > 0)
a diagonale zróbmy później, mamy błąd w dokumentacji i tam nie wspominamy o diagonalach, więc chwilowo możemy je pominąć dla oszczędności czasu

2022-12-19 18:27 UTC, kowalakk approved these changes

2022-12-21 17:12 UTC, merged